name: A workflow for my Hello World file
on:
  workflow_dispatch:
  
env:
  TEST: "1.2"

jobs:
  build:
    name: Hello world action
    runs-on: windows-latest
    steps:
      - name: Test summary action
        uses: wezzl0/writing-javascript-actions/.github/actions/issue-maker@${{env.TEST}}
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          joke: "Helo"
