name: A workflow for my Hello World file
on:
  workflow_dispatch:

jobs:
  build:
    name: Hello world action
    runs-on: windows-latest
    steps:
      - name: Overwrite Markdown
        run: |
          echo "Adding some Markdown content" >> $GITHUB_STEP_SUMMARY
          echo "There was an error, we need to clear the previous Markdown with some new content." > $GITHUB_STEP_SUMMARY
