name: A workflow for my Hello World file
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Hello world action
    runs-on: windows-latest
    steps:
      - run: echo ${{ runner.os == 'Linux' && 'bash' || 'powershell' }}
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
