name: A workflow for my Hello World file
on:
  workflow_dispatch:

jobs:
  build:
    name: Hello world action
    runs-on: windows-latest
    steps:
      - name: 1
        run: echo "Testing" >> $GITHUB_STEP_SUMMARY
      - name: 2
        run: echo $GITHUB_STEP_SUMMARY
      - name: 3
        run: echo "Testing" >> ${GITHUB_STEP_SUMMARY}
      - name: 4
        run: echo ${GITHUB_STEP_SUMMARY}
