name: A workflow for my Hello World file
on:
  workflow_dispatch:
  
env:
  TEST: 1.2

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: Test summary action
        uses: wezzl0/writing-javascript-actions/.github/actions/issue-maker@main
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          joke: "Helo"
      - name: testin
        run: |
          echo "$TEST"
          TEST = 1.3
          echo "$TEST"
      - name: testin 2
        run: echo "${{ env.TEST }}"
