name: A workflow for my Hello World file
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Hello world action
    runs-on: windows-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo "${{ github.event.action.ref }}"
   

