name: A workflow for my Hello World file
on:
  pull_request:
    types: [closed]

jobs:
  build:
    name: Hello world action
    runs-on: windows-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo "${{ github.event.merged }}"
          echo "${{ github.event.head.ref }}"
          echo "${{ github.event.pull_request.merged }}"
