name: A workflow for my Hello World file
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Hello world action
    runs-on: windows-latest
    steps:
      - run: echo ${{ github.repository }}
      - uses: actions/checkout@v1
        with:
          repository: 'wezzl0/Game_Engine_Asteroids'
      - run: echo ${{ github.repository }}

