name: A workflow for my Hello World file
on:
  workflow_dispatch:

jobs:
  build:
    name: Hello world action
    runs-on: windows-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo "${{ github.event.pull_request.merged }}"
          echo "${{ github.event.pull_request.head.ref }}"
          echo "$GITHUB_STEP_SUMMARY"
